name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: ${{ vars.ONTRACK_URL }}
          token: ${{ secrets.ONTRACK_TOKEN }}
          config: github.com
          indexation: 120
